# Generated by Django 5.0.2 on 2025-08-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("short_description", models.TextField(blank=True, max_length=500)),
                ("is_exist", models.BooleanField(default=True)),
                ("rating", models.FloatField(default=0.0)),
            ],
        ),
    ]
