# Generated by Django 5.2.4 on 2025-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landtime", "0003_brand_productimage_product_compare_at_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveIntegerField(
                default=24, help_text="Warranty length in months"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="landtime_pr_price_d3f7b0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="landtime_pr_created_82ed46_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="unique_primary_image_per_product",
            ),
        ),
    ]
